export const SET_ROUTE = "SET_ROUTE";
export const SET_USER = "SET_USER";
export const SET_LOGIN_EMAIL = "SET_LOGIN_EMAIL";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";
export const SET_SIGNUP_FIRST_NAME = "SET_SIGNUP_FIRST_NAME";
export const SET_SIGNUP_LAST_NAME = "SET_SIGNUP_LAST_NAME";
export const SET_SIGNUP_EMAIL = "SET_SIGNUP_EMAIL";
export const SET_SIGNUP_PASSWORD = "SET_SIGNUP_PASSWORD";
export const SET_SIGNUP_CONFIRM_PASSWORD = "SET_SIGNUP_CONFIRM_PASSWORD";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const SET_SIGNUP_ERROR_MESSAGE = "SET_SIGNUP_ERROR_MESSAGE";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_LOGIN_ERROR_MESSAGE = "SET_LOGIN_ERROR_MESSAGE";
export const SET_CSRF = "SET_CSRF";
export const RESET_STATE = "RESET_STATE";
export const SET_LOGIN_REMEMBER_ME = "SET_LOGIN_REMEMBER_ME";
export const SET_SIGNUP_REMEMBER_ME = "SET_SIGNUP_REMEMBER_ME";
export const SET_LOGIN_EMAIL_ERROR = "SET_LOGIN_EMAIL_ERROR";
export const SET_LOGIN_PASSWORD_ERROR = "SET_LOGIN_PASSWORD_ERROR";
export const SET_SIGNUP_FIRST_NAME_ERROR = "SET_SIGNUP_FIRST_NAME_ERROR";
export const SET_SIGNUP_LAST_NAME_ERROR = "SET_SIGNUP_LAST_NAME_ERROR";
export const SET_SIGNUP_EMAIL_ERROR = "SET_SIGNUP_EMAIL_ERROR";
export const SET_SIGNUP_PASSWORD_ERROR = "SET_SIGNUP_PASSWORD_ERROR";
export const SET_SIGNUP_CONFIRM_PASSWORD_ERROR = "SET_SIGNUP_CONFIRM_PASSWORD_ERROR";
export const SET_SIGNUP_PASSWORDS_MATCH_ERROR = "SET_SIGNUP_PASSWORDS_MATCH_ERROR";
export const SET_FORGOT_PASSWORD_EMAIL = "SET_FORGOT_PASSWORD_EMAIL";
export const SET_FORGOT_PASSWORD_ERROR = "SET_FORGOT_PASSWORD_ERROR";
export const SET_FORGOT_PASSWORD_ERROR_MESSAGE = "SET_FORGOT_PASSWORD_ERROR_MESSAGE";
export const SET_FORGOT_PASSWORD_EMAIL_ERROR = "SET_FORGOT_PASSWORD_EMAIL_ERROR";
export const SET_FORGOT_PASSWORD_EMAIL_SENT = "SET_FORGOT_PASSWORD_EMAIL_SENT";

export const SET_PASSWORD_RESET_PASSWORD = "SET_PASSWORD_RESET_PASSWORD";
export const SET_PASSWORD_RESET_CONFIRM_PASSWORD = "SET_PASSWORD_RESET_CONFIRM_PASSWORD";
export const SET_PASSWORD_RESET_TOKEN = "SET_PASSWORD_RESET_TOKEN";
export const SET_PASSWORD_RESET_PASSWORD_ERROR = "SET_PASSWORD_RESET_PASSWORD_ERROR";
export const SET_PASSWORD_RESET_CONFIRM_PASSWORD_ERROR = "SET_PASSWORD_RESET_CONFIRM_PASSWORD_ERROR";
export const SET_PASSWORD_RESET_PASSWORDS_MATCH_ERROR = "SET_PASSWORD_RESET_PASSWORDS_MATCH_ERROR";
export const SET_PASSWORD_RESET_ERROR = "SET_PASSWORD_RESET_ERROR";
export const SET_PASSWORD_RESET_ERROR_MESSAGE = "SET_PASSWORD_RESET_ERROR_MESSAGE";

export const SET_NAVIGATION_ACCOUNT_SELECTED = "SET_NAVIGATION_ACCOUNT_SELECTED";
export const SET_MOBILE_MENU = "SET_MOBILE_MENU";
export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";

export const SET_INITIAL_DATA = "SET_INITIAL_DATA";
export const SET_ROUTE_HOME = "SET_ROUTE_HOME";

export const SET_NAVIGATION_EDIT_PROFILE = "SET_NAVIGATION_EDIT_PROFILE";
export const SET_NAVIGATION_EDIT_EMAIL = "SET_NAVIGATION_EDIT_EMAIL";
export const SET_NAVIGATION_EDIT_PASSWORD = "SET_NAVIGATION_EDIT_PASSWORD";

export const SET_PROFILE_FIRST_NAME = "SET_PROFILE_FIRST_NAME";
export const SET_PROFILE_LAST_NAME = "SET_PROFILE_LAST_NAME";
export const SET_PROFILE_ADDRESS = "SET_PROFILE_ADDRESS";
export const SET_PROFILE_PHONE = "SET_PROFILE_PHONE";
export const SET_PROFILE_ABOUT = "SET_PROFILE_ABOUT";
export const SET_PROFILE_EMAIL = "SET_PROFILE_EMAIL";
export const SET_PROFILE_PASSWORD = "SET_PROFILE_PASSWORD";
export const SET_PROFILE_CONFIRM_PASSWORD = "SET_PROFILE_CONFIRM_PASSWORD";
export const SET_PROFILE_ERRORS_ERROR = "SET_PROFILE_ERRORS_ERROR";
export const SET_PROFILE_ERRORS_ERROR_MESSAGE = "SET_PROFILE_ERRORS_ERROR_MESSAGE";
export const SET_PROFILE_ERRORS_EMAIL_ERROR = "SET_PROFILE_ERRORS_EMAIL_ERROR";
export const SET_PROFILE_ERRORS_PASSWORD_ERROR = "SET_PROFILE_ERRORS_PASSWORD_ERROR";
export const SET_PROFILE_ERRORS_CONFIRM_PASSWORD_ERROR = "SET_PROFILE_ERRORS_CONFIRM_PASSWORD_ERROR";
export const SET_PROFILE_ERRORS_PASSWORDS_MATCH_ERROR = "SET_PROFILE_ERRORS_PASSWORDS_MATCH_ERROR";
export const SET_PROFILE_ERRORS_PASSWORD_CONFIRMATION_ERROR = "SET_PROFILE_ERRORS_PASSWORD_CONFIRMATION_ERROR";
export const SET_PROFILE_ERRORS_PASSWORD_CONFIRMATION_ERROR_MESSAGE = "SET_PROFILE_ERRORS_PASSWORD_CONFIRMATION_ERROR_MESSAGE";
export const SET_PROFILE_ERRORS_EMAIL_CONFIRMATION_ERROR = "SET_PROFILE_ERRORS_EMAIL_CONFIRMATION_ERROR";
export const SET_PROFILE_ERRORS_EMAIL_CONFIRMATION_ERROR_MESSAGE = "SET_PROFILE_ERRORS_EMAIL_CONFIRMATION_ERROR_MESSAGE";

export const SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA";
export const SET_USER_PROFILE_EMAIL = "SET_USER_PROFILE_EMAIL";





