export const SET_ROUTE = "SET_ROUTE";
export const SET_USER = "SET_USER";
export const SET_LOGIN_EMAIL = "SET_LOGIN_EMAIL";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";
export const SET_SIGNUP_FIRST_NAME = "SET_SIGNUP_FIRST_NAME";
export const SET_SIGNUP_LAST_NAME = "SET_SIGNUP_LAST_NAME";
export const SET_SIGNUP_EMAIL = "SET_SIGNUP_EMAIL";
export const SET_SIGNUP_PASSWORD = "SET_SIGNUP_PASSWORD";
export const SET_SIGNUP_CONFIRM_PASSWORD = "SET_SIGNUP_CONFIRM_PASSWORD";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";

